### PR TITLE
ci: only run push image for master branch

### PR DESCRIPTION
**Pull request by FrankYang0529**
https://github.com/longhorn/longhorn/issues/8039

### CODE REVIEW

**Comment by mantissahz** [comment]
@FrankYang0529,

We are still stuck at `Build and push image` for this PR.

**Comment by FrankYang0529** [comment]
> @FrankYang0529,
> 
> We are still stuck at `Build and push image` for this PR.

It's because we have "Required" tag on the task. If we remove it, we can pass it for this PR.

**Comment by FrankYang0529** [comment]
> > @FrankYang0529,
> > We are still stuck at `Build and push image` for this PR.
> 
> It's because we have "Required" tag on the task. If we remove it, we can pass it for this PR.

I just remove it and it works now.

**Comment by mantissahz** [comment]
@FrankYang0529, 
I also saw this in other Longhorn repos like

https://github.com/longhorn/longhorn-manager/blob/7e3b690713eb75fce1d386d0d6803324ecf88cdf/.github/workflows/build.yml#L9

Will other repositories have the same behavior (blocking the PR merged?)

**Review by a110605 — APPROVED** [review]
Looks good in this repo.

**Comment by FrankYang0529** [comment]
> @FrankYang0529,
> 
> I also saw this in other Longhorn repos like
> 
> https://github.com/longhorn/longhorn-manager/blob/7e3b690713eb75fce1d386d0d6803324ecf88cdf/.github/workflows/build.yml#L9
> 
> Will other repositories have the same behavior (blocking the PR merged?)

I think no. For other repositories, they really run some validation in PR, but for this repository, it only run docker build and we would like to do it only in master/main/version branches. We can see there is an `if` condition in the only job. That's why the CI doesn't run in PR.

**Comment by a110605** [comment]
@derekbit , I think this PR is good to merge for LH UI repo. WDYT?
cc @FrankYang0529

**Review by mantissahz — APPROVED** [review]
LGTM

**Pull request merged**
