### PR TITLE
feat(detach) Modify volume detach logic

### PR DESCRIPTION
**Pull request by smallteeths**
https://github.com/longhorn/longhorn/issues/6004

image: wangsiye/longhorn-ui:f5cea83

### CODE REVIEW

**Comment by innobead** [comment]
@PhanLe1010 Please help verify this. Thanks.

**Comment by PhanLe1010** [comment]
For the attach call, the request body should have `AttachmentID` set to `longhorn-ui` instead of the node name. For example:
```
{hostId: "phan-v133-pool2-60e83d12-8wv8r", AttachmentID: "longhorn-ui"}
```
For the detach call, the request body should have `AttachmentID` set to `longhorn-ui` and presenting the user with a check box for `ForceDetach`. Thank you very much

**Comment by PhanLe1010** [comment]
The attach call looks good now. 
However, the detach request still send hostID. Could you please make it so that ror the detach call, the request body should have `AttachmentID` set to `longhorn-ui` and presenting the user with a check box for `ForceDetach`. Other fields should be empty. Thank you very much

**Comment by PhanLe1010** [comment]
This image `wangsiye/longhorn-ui:d587dc7` LGTM

**Review by PhanLe1010 — APPROVED** [review]

**Pull request merged**
