### PR TITLE
feat(orphaned) Add orphaned data page

### PR DESCRIPTION
**Pull request by smallteeths**
https://github.com/longhorn/longhorn/issues/3826

image: wangsiye/longhorn-ui:3134d8b

Signed-off-by: Siye Wang <siye@rancher.com>

### CODE REVIEW

**Comment by innobead** [comment]
cc @derekbit

**Comment by derekbit** [comment]
Awesome!
Can we add a filter by Type? Thank you.

**Comment by derekbit** [comment]
Awesome! Thank you.

**Comment by derekbit** [comment]
Suggest some changes
1. Rename `Disk` to `Disk Name`
2. Rename `Path` to `Disk Path`
3. Add a `Disk Path` filter
4. Add `Directory Name` field (resource.spec.parameters[“DataName”])

Thank you. :)

**Comment by smallteeths** [comment]
Regarding point 5, as the fields will be different for different types, can we add a select component to the page to allow the user to switch between different types to display different types of tables Instead of displaying multiple tables.  @derekbit 

截屏2022-05-06 下午1 29 36

**Comment by derekbit** [comment]
> Regarding point 5, as the fields will be different for different types, can we add a select component to the page to allow the user to switch between different types to display different types of tables Instead of displaying multiple tables. @derekbit
> 
> 截屏2022-05-06 下午1 29 36

Perfect! Thank you ;)

**Comment by derekbit** [comment]
> Regarding point 5, as the fields will be different for different types, can we add a select component to the page to allow the user to switch between different types to display different types of tables Instead of displaying multiple tables. @derekbit
> 
> 截屏2022-05-06 下午1 29 36

Then we don't need the `Type` field.

**Review by derekbit — APPROVED** [review]
LGTM.

**Review by innobead — APPROVED** [review]
LGTM

**Pull request merged**
