### PR TITLE
fix(PV) Add storage class for PV

### PR DESCRIPTION
**Pull request by smallteeths**
https://github.com/longhorn/longhorn/issues/3506

image: wangsiye/longhorn-ui:79b50f6

### CODE REVIEW

**Comment by ChanYiLin** [comment]
Hi I have tested it, and there is one thing need to adjust

When I created PV/PVC from a restored Volume
I chose "use previous PVC" and left `StorageClassName` empty
The `StorageClassName` in payload send to backend would be `default`
but **it should be "" empty** string for backend to fill in the default longhorn storageClassName in setting.

Thanks!

**Comment by smallteeths** [comment]
> Hi I have tested it, and there is one thing need to adjust
> 
> When I created PV/PVC from a restored Volume I left `StorageClassName` empty The `StorageClassName` in payload send to backend would be `default` but **it should be "" empty** string for backend to fill in the default longhorn storageClassName in setting.
> 
> Thanks!

done 
new image: wangsiye/longhorn-ui:79b50f6

**Comment by ChanYiLin** [comment]
Hi @smallteeths 
I have tested it, LGTM, thanks!
cc @innobead

**Review by innobead — APPROVED** [review]
LGTM.

Thanks Jack and Siye.

**Pull request merged**
