### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by harryzcy**
I'm trying to work on the dark mode feature https://github.com/longhorn/longhorn/issues/2038, but found many dependencies are so old to work with. So bump them here first.

Major version updates:

Node version: require >= v18

Dependencies:

- `antd`: v3 to v5
- `axios`: v0 to v1
- `cron-parser`: v2 to v4
- `dva-loading`: v1 to v3
- `history`: v4 to v5
- `react-countup`: v4 to v6
- `react-helmet`: v5 to v6
- `react-markdown`: v4 to v8
- `react-resize-detector`: v1 to v9
- `sermer`: v5 to v7
- `recharts`: v1 to v2

devDependencies:

- `acorn`: v6 to v8
- `babel-loader`: v8 to v9
- `copy-webpack-plugin`: v4 to v12
- `cross-env`: v5 to v7
- `css-loader`: v2 to v6
- `cssnano`: v4 to v6
- `eslint`: v5 to v8
- `estraverse`: v4 to v5
- `file-loader`: v1 to v6
- `html-webpack-plugin`: v3 to v5
- `husky`: v8 to v9
- `jest`: v26 to v29
- `less`: v3 to v4
- `less-loader`: v4 to v12
- `mini-css-extract-plugin`: v0 to v2
- `progress-bar-webpack-plugin`: v1 to v2
- `sass-loader`: v7 to v14
- `string-replace-loader`: v2 to v3
- `style-loader`: v0 to v3
- `url-loader`: v1 to v4
- `webpack`: v4 to v5
- `webpack-cli`: v4 to v5
- `webpack-dev-server`: v3 to v4
- `webpack-manifest-plugin`: v3 to v5

### CODE REVIEW

**Comment by harryzcy** [comment]
This is so much technical debt to work with

**Comment by harryzcy** [comment]
The change is complete

**Comment by innobead** [comment]
@votdev could you help review this?

**Comment by votdev** [comment]
Thanks for the contribution.

But IMO it does not make sense to do a review and merge this huge changes before there is a PR that implements the main feature of https://github.com/longhorn/longhorn/issues/2038.

Without such PR, it is irresponsible to merge such a large number of changes without really needing them afterwards and with the risk of introducing regressions.

**Comment by harryzcy** [comment]
@votdev I feel upgrading dependencies are worthwhile though? Especially as Dependabot is giving many security alerts.

Do you think it's helpful to break down this PR into multiple smaller ones? I'm not sure how small they can be, but I can try.

**Comment by votdev** [comment]
> @votdev I feel upgrading dependencies are worthwhile though? Especially as Dependabot is giving many security alerts. They would need to be upgraded at some point anyways.

An upgrade makes sense, but this huge amount of changes, which could lead to regressions, shortly before the release of the next version is too dangerous in my opinion because there is not enough time left for testing. I think the feature makes more sense for v1.7 as there will be plenty of time for testing. @innobead What are your thoughts on that?

> Do you think it's helpful to break down this PR into multiple smaller ones?

No, do't split it. IMO it makes sense to have a separate PR for the UI changes/updates and another one that implements the "dark mode" feature.

**Comment by harryzcy** [comment]
All dependencies are up to date, except react (still 16), and react-markdown (requires react 18).
There still some UI issues to fix at this point

**Comment by innobead** [comment]
@scures Please review this.

**Comment by harryzcy** [comment]
@scures Thanks for reporting it. I'll take a look

**Pull request closed without merging**
