### PR TITLE
fix(volume) Add tooltip for 'Allow snapshots removal during trim'

### PR DESCRIPTION
**Pull request by smallteeths**
https://github.com/longhorn/longhorn/issues/5127

Signed-off-by: Siye Wang <siye@rancher.com>

### CODE REVIEW

**Review by innobead — CHANGES_REQUESTED** [review]
Add this tip to `SnapshotDataIntegrity` and `ReplicaAutoBalance` as well.

**Comment by smallteeths** [comment]
> Add this tip to `SnapshotDataIntegrity` and `ReplicaAutoBalance` as well.

done

**Review by innobead — APPROVED** [review]
LGTM

**Comment by innobead** [comment]
@Mergifyio backport v1.4.x

**Pull request merged**
