### PR TITLE
Check if node schedulable condition is set before trying to read it

### PR DESCRIPTION
**Pull request by Foritus**
One of my longhorn nodes is not currently schedulable due to kubernetes nonsense, and this has broken the whole UI as it throws an exception on page load due to one node being bad. Also a little formatting as those one-liners are getting out of control.

image

### CODE REVIEW

**Review by smallteeths — APPROVED** [review]
LGTM

**Review by innobead — APPROVED** [review]
LGMT.

@smallteeths Do you think if we can improve this kind of tedious null check in the future by using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining instead?

**Comment by innobead** [comment]
@weizhe0422 because @smallteeths is not around, please help create an issue and add a reference to this PR, and related backports as well. Thanks.

cc @longhorn/qa

**Comment by smallteeths** [comment]
> LGMT.
> 
> @smallteeths Do you think if we can improve this kind of tedious null check in the future by using https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining instead?

OK, Some browsers did not support the `?.` syntax well when the project was first established.  It should be all supported now, and I will improve this kind of tedious null check in the next version by using `?.`

**Pull request merged**
