### PR TITLE
feat(volume) Implement Replica Auto Balance Settings

### PR DESCRIPTION
**Pull request by smallteeths**
https://github.com/longhorn/longhorn/issues/2676

Signed-off-by: Siye Wang <siye@rancher.com>

### CODE REVIEW

**Comment by c3y1huang** [comment]
Clicking on the action dropdown `Update Replica Auto Balance` inside a specific volume seems to do no-op, but worked on the volume list page though.
screenshot-1

**Comment by c3y1huang** [comment]
And noticed UpdateReplicaCount is actually `Update Replica**s** Count`, I think it will look nicer if we move the replica auto-balance just below the update replicas count and also make the wordings consistent as `Update Replica**s** Auto Balance`?

**Comment by c3y1huang** [comment]
Can we also have the `Update Replica Auto Balance` for bulk action with the other `Update` actions?
Screenshot-2021-06-16-10:36:13

**Comment by smallteeths** [comment]
> Can we also have the `Update Replica Auto Balance` for bulk action with the other `Update` actions?
> Screenshot-2021-06-16-10:36:13

Yes, batch operations can be performed.

**Review by c3y1huang — APPROVED** [review]
LGTM

**Review by innobead — APPROVED** [review]
LGTM

**Pull request merged**
