### PR TITLE
Update backup wording and restore backing image modal

### PR DESCRIPTION
**Pull request by a110605**
### What this PR does / why we need it
From doc review feedback, update the wordings. 
See https://github.com/longhorn/website/pull/943#issuecomment-2224851099

### Issue
https://github.com/longhorn/longhorn/issues/7541

### Test Result
Screenshot 2024-07-12 at 4 44 07 PM

Screenshot 2024-07-12 at 4 39 29 PM

In volume detail page.
Screenshot 2024-07-12 at 4 20 52 PM

### Additional documentation or context
This PR should backport to v1.7.x

### CODE REVIEW

**Review by jillian-maroket — APPROVED** [review]
Thanks for implementing the changes I requested in the doc PR. I'll approve this now, but I want to mention that wording issues must be fixed in success messages.

Example:
> `message.success(`Successfully back up ${payload.name} backing image`

We should use the *past tense* when confirming that an action was completed. In this case, the verb should be "backed up".

**Comment by a110605** [comment]
> _past tense_

Thanks for advice, updated to `message.success(Successfully backed up ${payload.name} backing image`

**Review by jillian-maroket — APPROVED** [review]
LGTM. Thanks!

**Review by derekbit — APPROVED** [review]
LGTM

**Comment by derekbit** [comment]
@mergify backport v1.7.x

**Pull request merged**
