### PR TITLE
feat(volume) Add the engine image field to the volume list

### PR DESCRIPTION
**Pull request by smallteeths**
https://github.com/longhorn/longhorn/issues/3306

image: wangsiye/longhorn-ui:dd8637b

截屏2021-12-01 下午5 05 20

截屏2021-12-01 下午5 05 51

截屏2021-12-01 下午5 06 00

Signed-off-by: Siye Wang <siye@rancher.com>

### CODE REVIEW

**Comment by innobead** [comment]
@smallteeths Could we have a screenshot? Also fix this in the master branch first.

**Comment by smallteeths** [comment]
> @smallteeths Could we have a screenshot? Also fix this in the master branch first.

ok

**Comment by joshimoo** [comment]
cc @innobead can you clarify, I don't think this is what was requested?

**Comment by innobead** [comment]
> cc @innobead can you clarify, I don't think this is what was requested?

This is not like you guys discussed, but instead instance manager image.

**Pull request closed without merging**
