### PR TITLE
Add s390x support

### PR DESCRIPTION
**Pull request by thomasferrandiz**
This PR adds support to build on s390x architecture.

### CODE REVIEW

**Comment by innobead** [comment]
We are changing the image based on BCI, so this PR needs to be rebased later.

Could you check if Nginx package is able to support from BCI builtin repos? actively released?

**Comment by thomasferrandiz** [comment]
> 

nginx is available for SLES 15.3: https://scc.suse.com/packages/21182999
and I can confirm it it can be installed on the bci-base:15.3 image with the default repositories.

**Comment by innobead** [comment]
> > 
> 
> 
> 
> nginx is available for SLES 15.3: https://scc.suse.com/packages/21182999
> 
> and I can confirm it it can be installed on the bci-base:15.3 image with the default repositories. 

Is it actively released? What's the current version?

**Comment by thomasferrandiz** [comment]
nginx version in SLES 15.3 is 1.19.8-3.6.1 at the moment and it's in the SLE-Module-Server-Applications15-SP3-Updates
so it looks like it's actively maintained.

**Comment by innobead** [comment]
> nginx version in SLES 15.3 is 1.19.8-3.6.1 at the moment and it's in the SLE-Module-Server-Applications15-SP3-Updates so it looks like it's actively maintained.

@smallteeths will you have any concerns if we use this version instead of the current one 1.21.x?

**Comment by smallteeths** [comment]
> > nginx version in SLES 15.3 is 1.19.8-3.6.1 at the moment and it's in the SLE-Module-Server-Applications15-SP3-Updates so it looks like it's actively maintained.
> 
> @smallteeths will you have any concerns if we use this version instead of the current one 1.21.x?

longhorn-ui starts a web service with nginx, using the most basic configuration of nginx.As long as the current version of nginx has no CVE security holes, we can change the nginx version.

**Review by innobead — APPROVED** [review]

**Pull request merged**
