### PR TITLE
fix(recurring-job) Modify the interaction mode for force creating sna…

### PR DESCRIPTION
**Pull request by smallteeths**
https://github.com/longhorn/longhorn/issues/5610

### image

wangsiye/longhorn-ui:368fa09

### Demo

Jietu20230328-134850-HD

### CODE REVIEW

**Comment by innobead** [comment]
@smallteeths can we add a tip for `force create` for different types?

For snapshot, `Create snapshots periodically, even if expired snapshots cannot be cleaned up.`
For backup, `Create backups periodically, even if expired snapshots cannot be cleaned up.`

@mantissahz WDYT? 

cc @shuo-wu @c3y1huang

**Comment by mantissahz** [comment]
>For snapshot, Create snapshots periodically, even if expired snapshots cannot be cleaned up.
For backup, Create backups periodically, even if expired snapshots cannot be cleaned up.

That will be great if users could know what's the purpose for the `force create`

**Comment by smallteeths** [comment]
> @smallteeths can we add a tip for `force create` for different types?
> 
> For snapshot, `Create snapshots periodically, even if expired snapshots cannot be cleaned up.` For backup, `Create backups periodically, even if expired snapshots cannot be cleaned up.`
> 
> @mantissahz WDYT?
> 
> cc @shuo-wu @c3y1huang @khushboo-rancher

done

The longhorn-ui image is update to `wangsiye/longhorn-ui:3849cad`

Jietu20230328-152931-HD

**Comment by mantissahz** [comment]
Verified with wangsiye/longhorn-ui:3849cad.

**Review by innobead — APPROVED** [review]

**Comment by innobead** [comment]
@Mergifyio backport v1.4.x v1.3.x

**Pull request merged**
