### PR TITLE
[Master]feat(recurring job) Recurring Jobs support snapshot-deletion and snap…

### PR DESCRIPTION
**Pull request by smallteeths**
https://github.com/longhorn/longhorn/issues/5272

### CODE REVIEW

**Comment by c3y1huang** [comment]
Screenshot-2023-02-21-09:52:53

Can we have the task prefixed with `Snapshot` together? ex:
```
Backup
Snapshot
Snapshot Cleanup
Snapshot Delete
```

**Comment by smallteeths** [comment]
> 

Ok

**Comment by smallteeths** [comment]
> Screenshot-2023-02-21-09:52:53
> 
> Can we have the task prefixed with `Snapshot` together? ex:
> 
> ```
> Backup
> Snapshot
> Snapshot Cleanup
> Snapshot Delete
> ```

OK

**Comment by c3y1huang** [comment]
LGTM, verified with `wangsiye/longhorn-ui:a98350a`.

**Review by innobead — APPROVED** [review]

**Comment by c3y1huang** [comment]
@Mergifyio backport v1.4.x

**Comment by c3y1huang** [comment]
> @Mergifyio backport v1.4.x

I guess Mergifyio not here? @innobead ?

**Comment by innobead** [comment]
@Mergifyio backport v1.4.x

**Comment by smallteeths** [comment]
> > @Mergifyio backport v1.4.x
> 
> ~I guess we don't have @Mergifyio here?~ Seems we have @Mergifyio here, but I cannot use it. Ref: [#588 (comment)](https://github.com/longhorn/longhorn-ui/pull/588#issuecomment-1366333712)
> 
> cc @innobead @smallteeths

I will manually make the backport changes.

**Comment by c3y1huang** [comment]
@Mergifyio backport v1.4.x

**Comment by innobead** [comment]
@Mergifyio backport v1.4.x

**Comment by c3y1huang** [comment]
@Mergifyio backport v1.3.x

**Comment by innobead** [comment]
https://github.com/Mergifyio backport v1.3.x

**Pull request merged**
